title: Welcome to my blog
author: Le Aundre Jackson
email: leaundre.jackson87@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is a test blog I've created for learning Github pages

# social links
twitter_username: Dre_MF_Jackson
github_username:  Jacksole

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
